name: Docker Login

on: 
  workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Nginx image from Docker Hub
        run: docker pull nginx:latest

      - name: Docker new name
        run: docker tag nginx:latest ${{ vars.DOCKER_USERNAME }}/custom-nginx:latest

      - name: Push image to Docker Hub
        run: docker push ${{ vars.DOCKER_USERNAME }}/custom-nginx:latest
