name : Docker Login with github actions

on: workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest
  steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -name: Pull nginx from DockerHub
       run: docker pull nginx:latest 
       
      -name: Renaming nginx Image name
       run: docker tag nginx:latest ${{ vars.DOCKER_USERNAME }}
       
      -name: Push Latest image intlo Docker hub
       run: docker push ${{ vars.DOCKER_USERNAME }}
