name : Docker Login with github actions

on :workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -name: Pull Nginix from DockerHub
       run: docker pull nginix:latest 
       
      -name: Renaming Nginix Image name
       run: docker tag nginix:latest ${{ vars.DOCKER_USERNAME }}
       
      -name: Push Latest image intlo Docker hub
       run: docker push ${{ vars.DOCKER_USERNAME }}
